version: "3.3"

services:

  database:
    build: ./database/
    restart: always
    tty: true

  gunicorn:
    build: ./django/
    restart: always
    tty: true
    expose:
      - "7777"
    volumes:
      - "static:/static/"
    links:
      - database
    command: bash -c "python manage.py collectstatic --noinput && python manage.py makemigrations && python manage.py migrate && /usr/local/bin/gunicorn -w 2 -b :7777 dz2.wsgi"

  nginx:
    build: ./nginx/
    restart: always
    tty: true
    ports:
      - "80:80"
    volumes:
      - "static:/www/static"
    links:
      - gunicorn

volumes:
  static:


